#!/usr/bin/env bash
set -euo pipefail

# Adds a new user to sing-box server config and exports ready client configs.
# Intended to run ON the VPS where sing-box is installed.

usage() {
  cat >&2 <<'EOF'
Usage:
  sudo bash vpn_install/add_user.sh --platform <iphone|windows|android|macos> --user <name>

What it does:
- generates credentials for a new user
- appends the user to /etc/sing-box/config.json for:
    * VLESS+Reality (uuid)
    * Trojan (password)
    * Hysteria2 (password)
- restarts sing-box
- exports ready-to-import client configs into:
    /etc/sing-box/users/<platform>/<user>/

Notes:
- Requires: jq, openssl, systemd
- Expects baseline templates generated by vpn_install/setup.sh in:
    /etc/sing-box/client-configs/<platform>/
EOF
}

PLATFORM=""
USERNAME=""
while [[ $# -gt 0 ]]; do
  case "$1" in
    --platform) PLATFORM="$2"; shift 2;;
    --user|--username) USERNAME="$2"; shift 2;;
    -h|--help) usage; exit 0;;
    *) echo "Unknown arg: $1" >&2; usage; exit 2;;
  esac
done

if [[ -z "$PLATFORM" || -z "$USERNAME" ]]; then
  usage
  exit 2
fi

case "$PLATFORM" in
  iphone|windows|android|macos) ;;
  *) echo "Invalid platform: $PLATFORM" >&2; exit 2;;
esac

CONF="/etc/sing-box/config.json"
BASE_DIR="/etc/sing-box/client-configs/${PLATFORM}"
OUT_DIR="/etc/sing-box/users/${PLATFORM}/${USERNAME}"

if [[ ! -f "$CONF" ]]; then
  echo "Missing $CONF" >&2
  exit 3
fi
if [[ ! -d "$BASE_DIR" ]]; then
  echo "Missing templates directory: $BASE_DIR" >&2
  echo "Run vpn_install/setup.sh first." >&2
  exit 3
fi

VLESS_UUID="$(cat /proc/sys/kernel/random/uuid)"
TROJAN_PASSWORD="$(openssl rand -base64 24 | tr -d '=+/\n' | head -c 32)"
HYSTERIA2_PASSWORD="$(openssl rand -base64 24 | tr -d '=+/\n' | head -c 32)"

TMP="$(mktemp)"
trap 'rm -f "$TMP"' EXIT

# Append users (idempotency check by exact match)
# vless user list: inbounds[] where tag==vless-reality, field .users[] with uuid
jq --arg uuid "$VLESS_UUID" \
   --arg tpass "$TROJAN_PASSWORD" \
   --arg hname "$USERNAME" \
   --arg hpass "$HYSTERIA2_PASSWORD" \
'
  .inbounds |= (map(
    if .tag=="vless-reality" then
      .users |= (if (map(.uuid) | index($uuid)) then . else . + [{"uuid":$uuid,"flow":"xtls-rprx-vision"}] end)
    elif .tag=="trojan-tls" then
      .users |= (if (map(.password) | index($tpass)) then . else . + [{"password":$tpass}] end)
    elif .tag=="hysteria2" then
      .users |= (if (map(.name) | index($hname)) then . else . + [{"name":$hname,"password":$hpass}] end)
    else . end
  ))
' "$CONF" >"$TMP"

install -m 0640 -o root -g singbox "$TMP" "$CONF"

systemctl restart sing-box

# Export client configs
install -d -m 0755 "$OUT_DIR"

# VLESS
jq --arg uuid "$VLESS_UUID" '.outbounds |= (map(if .tag=="proxy" and .type=="vless" then .uuid=$uuid else . end))' \
  "$BASE_DIR/vless_reality_443.json" >"$OUT_DIR/vless_reality_443.json"

# Trojan
jq --arg pass "$TROJAN_PASSWORD" '.outbounds |= (map(if .tag=="proxy" and .type=="trojan" then .password=$pass else . end))' \
  "$BASE_DIR/trojan_2053.json" >"$OUT_DIR/trojan_2053.json"

# Hysteria2
jq --arg pass "$HYSTERIA2_PASSWORD" '.outbounds |= (map(if .tag=="proxy" and .type=="hysteria2" then .password=$pass else . end))' \
  "$BASE_DIR/hysteria2_443udp.json" >"$OUT_DIR/hysteria2_443udp.json"

chmod 0644 "$OUT_DIR"/*.json

cat <<EOF
OK
User: ${USERNAME}
Platform: ${PLATFORM}
Exported to: ${OUT_DIR}

Credentials:
- VLESS_UUID=${VLESS_UUID}
- TROJAN_PASSWORD=${TROJAN_PASSWORD}
- HYSTERIA2_PASSWORD=${HYSTERIA2_PASSWORD}
EOF
